CC = gcc
CFLAGS = -Wall -g
TARGET = app

all:
	$(info Enter a recipe to run like "Make LinearSearch")
	$(info All the executables will be named as app.exe)

LinearSearch: LinearSearch.c
	$(CC) $(CFLAGS) -o $(TARGET) LinearSearch.c

BinarySearch: BinarySearch.c
	$(CC) $(CFLAGS) -o $(TARGET) BinarySearch.c